// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// source: proto/sssmemvault.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single secret entry stored in the vault
// Represents a list of fragments, typically associated with one owner IP.
type FragmentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fragments     [][]byte               `protobuf:"bytes,1,rep,name=fragments,proto3" json:"fragments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FragmentList) Reset() {
	*x = FragmentList{}
	mi := &file_proto_sssmemvault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentList) ProtoMessage() {}

func (x *FragmentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentList.ProtoReflect.Descriptor instead.
func (*FragmentList) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{0}
}

func (x *FragmentList) GetFragments() [][]byte {
	if x != nil {
		return x.Fragments
	}
	return nil
}

// Represents a single secret entry stored in the vault
type Entry struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp   `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key            string                   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Readers        []string                 `protobuf:"bytes,3,rep,name=readers,proto3" json:"readers,omitempty"`                                                                                                               // List of node names allowed to get decoded fragments
	OwnerFragments map[string]*FragmentList `protobuf:"bytes,4,rep,name=owner_fragments,json=ownerFragments,proto3" json:"owner_fragments,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Map: Owner Name -> List of Encrypted SSS Fragments
	Threshold      int32                    `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`                                                                                                          // Number of fragments required to reconstruct the secret
	Signature      []byte                   `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`                                                                                                           // Master public key signature over the entry data (excluding this field)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_sssmemvault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetReaders() []string {
	if x != nil {
		return x.Readers
	}
	return nil
}

func (x *Entry) GetOwnerFragments() map[string]*FragmentList {
	if x != nil {
		return x.OwnerFragments
	}
	return nil
}

func (x *Entry) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Entry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Metadata for an entry, used in ListResponse
type EntryMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryMetadata) Reset() {
	*x = EntryMetadata{}
	mi := &file_proto_sssmemvault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryMetadata) ProtoMessage() {}

func (x *EntryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryMetadata.ProtoReflect.Descriptor instead.
func (*EntryMetadata) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{2}
}

func (x *EntryMetadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EntryMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Request message for the List RPC
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_sssmemvault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{3}
}

// Response message for the List RPC
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*EntryMetadata       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_sssmemvault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetEntries() []*EntryMetadata {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Request message for the Get RPC
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_sssmemvault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Response message for the Get RPC
type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_sssmemvault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Request message for the GetDecoded RPC
type GetDecodedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDecodedRequest) Reset() {
	*x = GetDecodedRequest{}
	mi := &file_proto_sssmemvault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecodedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecodedRequest) ProtoMessage() {}

func (x *GetDecodedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecodedRequest.ProtoReflect.Descriptor instead.
func (*GetDecodedRequest) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{7}
}

func (x *GetDecodedRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GetDecodedRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Response message for the GetDecoded RPC
type GetDecodedResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EncryptedFragments [][]byte               `protobuf:"bytes,1,rep,name=encrypted_fragments,json=encryptedFragments,proto3" json:"encrypted_fragments,omitempty"` // The SSS fragments, decrypted by the owner node and then re-encrypted for the requestor using the requestor's hybrid public key.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDecodedResponse) Reset() {
	*x = GetDecodedResponse{}
	mi := &file_proto_sssmemvault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDecodedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDecodedResponse) ProtoMessage() {}

func (x *GetDecodedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDecodedResponse.ProtoReflect.Descriptor instead.
func (*GetDecodedResponse) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{8}
}

func (x *GetDecodedResponse) GetEncryptedFragments() [][]byte {
	if x != nil {
		return x.EncryptedFragments
	}
	return nil
}

// Request message for the Push RPC
type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *Entry                 `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"` // The full entry, signed by the master key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_proto_sssmemvault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{9}
}

func (x *PushRequest) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Response message for the Push RPC (currently empty)
type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_proto_sssmemvault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sssmemvault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_proto_sssmemvault_proto_rawDescGZIP(), []int{10}
}

var File_proto_sssmemvault_proto protoreflect.FileDescriptor

const file_proto_sssmemvault_proto_rawDesc = "" +
	"\n" +
	"\x17proto/sssmemvault.proto\x12\vsssmemvault\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\fFragmentList\x12\x1c\n" +
	"\tfragments\x18\x01 \x03(\fR\tfragments\"\xd8\x02\n" +
	"\x05Entry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\areaders\x18\x03 \x03(\tR\areaders\x12O\n" +
	"\x0fowner_fragments\x18\x04 \x03(\v2&.sssmemvault.Entry.OwnerFragmentsEntryR\x0eownerFragments\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x1a\\\n" +
	"\x13OwnerFragmentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.sssmemvault.FragmentListR\x05value:\x028\x01\"[\n" +
	"\rEntryMetadata\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\r\n" +
	"\vListRequest\"D\n" +
	"\fListResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.sssmemvault.EntryMetadataR\aentries\"X\n" +
	"\n" +
	"GetRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"7\n" +
	"\vGetResponse\x12(\n" +
	"\x05entry\x18\x01 \x01(\v2\x12.sssmemvault.EntryR\x05entry\"_\n" +
	"\x11GetDecodedRequest\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"E\n" +
	"\x12GetDecodedResponse\x12/\n" +
	"\x13encrypted_fragments\x18\x01 \x03(\fR\x12encryptedFragments\"7\n" +
	"\vPushRequest\x12(\n" +
	"\x05entry\x18\x01 \x01(\v2\x12.sssmemvault.EntryR\x05entry\"\x0e\n" +
	"\fPushResponse2\x90\x02\n" +
	"\vSssMemVault\x12;\n" +
	"\x04List\x12\x18.sssmemvault.ListRequest\x1a\x19.sssmemvault.ListResponse\x128\n" +
	"\x03Get\x12\x17.sssmemvault.GetRequest\x1a\x18.sssmemvault.GetResponse\x12M\n" +
	"\n" +
	"GetDecoded\x12\x1e.sssmemvault.GetDecodedRequest\x1a\x1f.sssmemvault.GetDecodedResponse\x12;\n" +
	"\x04Push\x12\x18.sssmemvault.PushRequest\x1a\x19.sssmemvault.PushResponseB%Z#github.com/fingon/sssmemvault/protob\x06proto3"

var (
	file_proto_sssmemvault_proto_rawDescOnce sync.Once
	file_proto_sssmemvault_proto_rawDescData []byte
)

func file_proto_sssmemvault_proto_rawDescGZIP() []byte {
	file_proto_sssmemvault_proto_rawDescOnce.Do(func() {
		file_proto_sssmemvault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sssmemvault_proto_rawDesc), len(file_proto_sssmemvault_proto_rawDesc)))
	})
	return file_proto_sssmemvault_proto_rawDescData
}

var file_proto_sssmemvault_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_sssmemvault_proto_goTypes = []any{
	(*FragmentList)(nil),          // 0: sssmemvault.FragmentList
	(*Entry)(nil),                 // 1: sssmemvault.Entry
	(*EntryMetadata)(nil),         // 2: sssmemvault.EntryMetadata
	(*ListRequest)(nil),           // 3: sssmemvault.ListRequest
	(*ListResponse)(nil),          // 4: sssmemvault.ListResponse
	(*GetRequest)(nil),            // 5: sssmemvault.GetRequest
	(*GetResponse)(nil),           // 6: sssmemvault.GetResponse
	(*GetDecodedRequest)(nil),     // 7: sssmemvault.GetDecodedRequest
	(*GetDecodedResponse)(nil),    // 8: sssmemvault.GetDecodedResponse
	(*PushRequest)(nil),           // 9: sssmemvault.PushRequest
	(*PushResponse)(nil),          // 10: sssmemvault.PushResponse
	nil,                           // 11: sssmemvault.Entry.OwnerFragmentsEntry
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_sssmemvault_proto_depIdxs = []int32{
	12, // 0: sssmemvault.Entry.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: sssmemvault.Entry.owner_fragments:type_name -> sssmemvault.Entry.OwnerFragmentsEntry
	12, // 2: sssmemvault.EntryMetadata.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 3: sssmemvault.ListResponse.entries:type_name -> sssmemvault.EntryMetadata
	12, // 4: sssmemvault.GetRequest.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 5: sssmemvault.GetResponse.entry:type_name -> sssmemvault.Entry
	12, // 6: sssmemvault.GetDecodedRequest.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 7: sssmemvault.PushRequest.entry:type_name -> sssmemvault.Entry
	0,  // 8: sssmemvault.Entry.OwnerFragmentsEntry.value:type_name -> sssmemvault.FragmentList
	3,  // 9: sssmemvault.SssMemVault.List:input_type -> sssmemvault.ListRequest
	5,  // 10: sssmemvault.SssMemVault.Get:input_type -> sssmemvault.GetRequest
	7,  // 11: sssmemvault.SssMemVault.GetDecoded:input_type -> sssmemvault.GetDecodedRequest
	9,  // 12: sssmemvault.SssMemVault.Push:input_type -> sssmemvault.PushRequest
	4,  // 13: sssmemvault.SssMemVault.List:output_type -> sssmemvault.ListResponse
	6,  // 14: sssmemvault.SssMemVault.Get:output_type -> sssmemvault.GetResponse
	8,  // 15: sssmemvault.SssMemVault.GetDecoded:output_type -> sssmemvault.GetDecodedResponse
	10, // 16: sssmemvault.SssMemVault.Push:output_type -> sssmemvault.PushResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_sssmemvault_proto_init() }
func file_proto_sssmemvault_proto_init() {
	if File_proto_sssmemvault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sssmemvault_proto_rawDesc), len(file_proto_sssmemvault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sssmemvault_proto_goTypes,
		DependencyIndexes: file_proto_sssmemvault_proto_depIdxs,
		MessageInfos:      file_proto_sssmemvault_proto_msgTypes,
	}.Build()
	File_proto_sssmemvault_proto = out.File
	file_proto_sssmemvault_proto_goTypes = nil
	file_proto_sssmemvault_proto_depIdxs = nil
}
